apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
  flatdb-username: {{ .Values.flatdb.username | b64enc }}
  flatdb-password: {{ .Values.flatdb.password | b64enc }}
