apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: DEPLOYMENTNAME
  namespace: NAMESPACE
  labels:
    app: DEPLOYMENTNAME
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: DEPLOYMENTNAME
        image: elasticsearch:5.6
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: bootstrap.memory_lock
          value: "true"
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: DISCOVERY_SERVICE
          value: DEPLOYMENTNAME-discovery
        - name: HTTP_CORS_ENABLE
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          value: "*"
        - name: NETWORK_HOST
          value: "_eth0:ipv4_"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_MASTER
          value: "true"
        - name: path.repo
          value: "/backups"
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        resources:
          limits:
            cpu: 2
            memory: "5Gi"
          requests:
            cpu: 200m
            memory: "2.5Gi"
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
          - name: elasticsearch-configmap
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          - name: elasticsearch-storage
            mountPath: /usr/share/elasticsearch/data/
      volumes:
        - name: elasticsearch-configmap
          configMap:
            name: DEPLOYMENTNAME-config
      securityContext:
        fsGroup: 1000
      nodeSelector:
        cloud.google.com/gke-nodepool: himem-pool
  serviceName: DEPLOYMENTNAME
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
