apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: DEPLOYMENTNAME
  namespace: NAMESPACE
  labels:
    app: DEPLOYMENTNAME
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: install-gcs-repository
        image: elasticsearch:5.6
        command: ["bin/elasticsearch-plugin", "install", "repository-gcs"]
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: elasticsearch-plugins
            mountPath: /usr/share/elasticsearch/plugins/
      - name: install-gcs-service-account
        image: elasticsearch:5.6
        command: ["sh", "-c", "bin/elasticsearch-keystore create;  bin/elasticsearch-keystore add-file gcs.client.default.credentials_file /var/secrets/google/key.json; chown elasticsearch /etc/elasticsearch/elasticsearch.keystore"]
        volumeMounts:
          - name: gcs-credentials
            mountPath: /var/secrets/google
          - name: elasticsearch-keystore
            mountPath: /etc/elasticsearch/
      containers:
      - name: DEPLOYMENTNAME
        image: elasticsearch:5.6
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: bootstrap.memory_lock
          value: "true"
        - name: CLUSTER_NAME
          value: DEPLOYMENTNAME-es
        - name: MINIMUM_MASTER_NODES
          value: "1"
        - name: DISCOVERY_SERVICE
          value: DEPLOYMENTNAME-discovery
        - name: HTTP_CORS_ENABLE
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          value: "*"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        resources:
          limits:
            cpu: 2
            memory: "3Gi"
          requests:
            cpu: 200m
            memory: "2.5Gi"
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
          - name: elasticsearch-configmap
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          - name: elasticsearch-keystore
            mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
            subPath: elasticsearch.keystore
          - name: elasticsearch-plugins
            mountPath: /usr/share/elasticsearch/plugins/
          - name: elasticsearch-storage
            mountPath: /usr/share/elasticsearch/data/
      volumes:
        - name: elasticsearch-configmap
          configMap:
            name: DEPLOYMENTNAME-config
        - name: elasticsearch-keystore
          emptyDir: {}
        - name: elasticsearch-plugins
          emptyDir: {}
        - name: gcs-credentials
          secret:
            secretName: DEPLOYMENTNAME-secret
      securityContext:
        fsGroup: 101
      nodeSelector:
        cloud.google.com/gke-nodepool: himem-pool
  serviceName: DEPLOYMENTNAME
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
