apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME-exporter
  namespace: NAMESPACE
  annotations:
      prometheus.io/scrape: 'true'
spec:
  selector: 
    app: SERVICENAME-exporter
  ports:
    - port: 9114
      targetPort: 9114 
