apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME-discovery
  namespace: NAMESPACE
  labels:
    app: SERVICENAME
spec:
  clusterIP: None
  selector:
    app: SERVICENAME
  ports:
  - port: 9300
    protocol: TCP
    targetPort: 9300
    name: transport
  publishNotReadyAddresses: true
  type: ClusterIP
