apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: "NAMESPACE"
  labels:
    app: "SERVICENAME"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: SERVICENAME
  type: ClusterIP
