apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8080",
          "--backend=NAMESPACE-gui.NAMESPACE.svc.cluster.local:80",
          "--service=vocabularies-dev.cessda.eu",
          "--rollout_strategy=managed"
        ]
        ports:
         - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 40Mi
          limits:
            cpu: 200m
            memory: 128Mi
