apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: gesis/stardat-ddiflatdb:3.5.0
        env:
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DEPLOYMENTNAME-secret
              key: password
        ports:
        - containerPort: 8080
          name: frontend-cport
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          limits:
            cpu: 200m
            memory: 800Mi
      nodeSelector:
        cloud.google.com/gke-nodepool : default-pool
