kind: Service
apiVersion: v1
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
spec:
  type: ClusterIP
  ports:
  - name: frontend-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: SERVICENAME
