{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flatdb.serviceAccountName" . }}
  labels:
{{ include "flatdb.labels" . | nindent 4 }}
{{- end -}}
