apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  labels:
    app: SERVICENAME
  name: SERVICENAME
spec:
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  selector:
    app: SERVICENAME
