apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret: WmpZeU9UZzRPR1V5TURNNU1qUTFOekZrT1Rrek1HWmpZVGRrWWpJek1EVTVNbVZtTlRnMlpXTTVNalJtTVRneVpUVXhZemswWWpreU1UZzNPREExTnpkbVlUYzBPREV5WWpBd05UYzNaRGxoTWpVNE1qSXhNV1UxWVRnME5UVmxPRGt6T1RVd05qRmxObUk1WkdFM1ltSTFaV0psTTJNelpqQTBPR1EyT1dJPQ==
