apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  replicas: 1
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: IMAGETAG
        imagePullPolicy: Always
        env:
        - name: DDIFLATDB_REST_URL
          value: http://NAMESPACE-flatdb:8080
        - name: LOGGING_LEVEL_ROOT
          value: INFO
        - name: LOGGING_LEVEL_ORG_ELASTICSEARCH
          value: INFO
        - name: LOGGING_LEVEL_ORG_GESIS_WTS
          value: INFO
        - name: LOGGING_LEVEL_EU_CESSDA_CVMANAGER
          value: INFO
        - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
          value: INFO
        - name: SPRING_DATA_ELASTICSEARCH_CLUSTERNAME
          value: NAMESPACE-es
        - name: SPRING_DATA_ELASTICSEARCH_CLUSTERNODES
          value: NAMESPACE-es:9300
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://NAMESPACE-mysql:3306/cvmanager-security?useSSL=false&amp;useUnicode=yes&amp;characterEncoding=UTF-8
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: DEPLOYMENTNAME-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DEPLOYMENTNAME-secret
              key: password
        - name: SPRING_MAIL_HOST
          value: DEPLOYMENTNAME-mailrelay
        ports:
        - containerPort: 8080
          name: frontend-cport
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2.25Gi
          limits:
            cpu: 1
            memory: 2.25Gi
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
