apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: DEPLOYMENTNAME
  replicas: 1
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: IMAGETAG
        imagePullPolicy: Always
        env:
        - name: DC_ENV
          value: ENVIRONMENT
        - name: logging.level.ROOT
          value: INFO
        - name: logging.level.org.elasticsearch
          value: INFO
        - name: org.gesis.wts
          value: INFO
        - name: eu.cessda.cvmanager
          value: INFO
        - name: org.hibernate.SQL
          value: INFO
        ports:
        - containerPort: 8080
          name: frontend-cport
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2.25Gi
          limits:
            cpu: 1
            memory: 2.25Gi
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
