apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "es.fullname" . }}-config
  labels:
    {{- include "es.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/elasticsearch.yml").AsConfig | indent 2 }}
