apiVersion: v1
kind: Secret
metadata:
  name: {{ include "es.fullname" . }}-secret
  labels:
    {{- include "es.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secret/key.json").AsSecrets | indent 2 }}